version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ahl-allah-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ahl_allah_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/setup-postgresql.sql:/docker-entrypoint-initdb.d/setup.sql

  # Node.js Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ahl-allah-server-dev
    restart: unless-stopped
    ports:
      - "60772:60772"
    environment:
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ahl_allah_db
      DB_USER: postgres
      DB_PASSWORD: password
      
      # JWT Configuration
      JWT_SECRET: ByYM000OLlMQG6VVVp1OH7Xzyr7gHuw1qvUC5dcGt3SNM
      JWT_EXPIRES_IN: 7d
      JWT_ISSUER: http://localhost:60772
      JWT_AUDIENCE: http://localhost:4200
      
      # Email Configuration
      EMAIL_FROM: a99.bdr@gmail.com
      EMAIL_SMTP_SERVER: smtp.gmail.com
      EMAIL_PORT: 465
      EMAIL_USERNAME: a99.bdr@gmail.com
      EMAIL_PASSWORD: acxv mzkd ipin wmyn
      
      # Server Configuration
      PORT: 60772
      NODE_ENV: development
      SESSION_SECRET: your-session-secret-key
      
      # Frontend Configuration
      FRONTEND_URL: http://localhost:4200
      
      # File Upload
      UPLOAD_PATH: ./uploads
      MAX_FILE_SIZE: 5242880
      
      # Phone Number Auth Configuration
      TWILIO_ACCOUNT_SID: your_twilio_account_sid
      TWILIO_AUTH_TOKEN: your_twilio_auth_token
      TWILIO_PHONE_NUMBER: +1234567890
      TWILIO_WHATSAPP_NUMBER: whatsapp:+14155238886
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    command: npm run dev

volumes:
  postgres_dev_data:

